
var MockTypeData = [
	{
		id: 1,
		imgURL: "app/style/images/colorful.png",
		imgURLActive: "app/style/images/colorful_active.png",
		items: [
			{
				id: 1,
				title: "番石榴西瓜汁",
				subTitle: "Guava Watermelon",
				imgURL: "itemIMG/watermelon.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				capacity: 400,
				price: 19
			},
			{
				id: 2,
				title: "番石榴西瓜汁",
				subTitle: "Guava Watermelon",
				imgURL: "itemIMG/watermelon.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				capacity: 400,
				price: 19
			},
			{
				id: 3,
				title: "番石榴西瓜汁",
				subTitle: "Guava Watermelon",
				imgURL: "itemIMG/watermelon.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				capacity: 400,
				price: 19
			},
			{
				id: 4,
				title: "番石榴西瓜汁",
				subTitle: "Guava Watermelon",
				imgURL: "itemIMG/watermelon.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				capacity: 400,
				price: 19
			},
			{
				id: 5,
				title: "番石榴西瓜汁",
				subTitle: "Guava Watermelon",
				imgURL: "itemIMG/watermelon.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				capacity: 400,
				price: 19
			},
			{
				id: 6,
				title: "番石榴西瓜汁",
				subTitle: "Guava Watermelon",
				imgURL: "itemIMG/watermelon.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				capacity: 400,
				price: 19
			},
		]
	},
	{
		id: 2,
		imgURL: "app/style/images/double.png",
		imgURLActive: "app/style/images/double_active.png",
		items: [
			{
				id: 7,
				title: "凤梨鲜橙汁",
				subTitle: "Pinapple Orange",
				imgURL: "itemIMG/pinapple.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 20,
				capacity: 400,
			},
			{
				id: 8,
				title: "凤梨鲜橙汁",
				subTitle: "Pinapple Orange",
				imgURL: "itemIMG/pinapple.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 20,
				capacity: 400,
			},
			{
				id: 9,
				title: "凤梨鲜橙汁",
				subTitle: "Pinapple Orange",
				imgURL: "itemIMG/pinapple.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 20,
				capacity: 400,
			},
			{
				id: 10,
				title: "凤梨鲜橙汁",
				subTitle: "Pinapple Orange",
				imgURL: "itemIMG/pinapple.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 20,
				capacity: 400,
			},
			{
				id: 11,
				title: "凤梨鲜橙汁",
				subTitle: "Pinapple Orange",
				imgURL: "itemIMG/pinapple.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 20,
				capacity: 400,
			},
			{
				id: 12,
				title: "凤梨鲜橙汁",
				subTitle: "Pinapple Orange",
				imgURL: "itemIMG/pinapple.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 20,
				capacity: 400,
			},
		]
	},
	{
		id: 3,
		imgURL: "app/style/images/probiotics.gif",
		imgURLActive: "app/style/images/probiotics_active.png",
		items: [
			{
				id: 13,
				title: "牛油果雪梨",
				subTitle: "Avocado Pear",
				imgURL: "itemIMG/pear.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 23,
				capacity: 400,
			},
			{
				id: 14,
				title: "牛油果雪梨",
				subTitle: "Avocado Pear",
				imgURL: "itemIMG/pear.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 23,
				capacity: 400,
			},
			{
				id: 15,
				title: "牛油果雪梨",
				subTitle: "Avocado Pear",
				imgURL: "itemIMG/pear.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 23,
				capacity: 400,
			},
			{
				id: 16,
				title: "牛油果雪梨",
				subTitle: "Avocado Pear",
				imgURL: "itemIMG/pear.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 23,
				capacity: 400,
			},
			{
				id: 17,
				title: "牛油果雪梨",
				subTitle: "Avocado Pear",
				imgURL: "itemIMG/pear.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 23,
				capacity: 400,
			},
			{
				id: 18,
				title: "牛油果雪梨",
				subTitle: "Avocado Pear",
				imgURL: "itemIMG/pear.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 23,
				capacity: 400,
			},
		]
	},
	{
		id: 4,
		imgURL: "app/style/images/yogurt.gif",
		imgURLActive: "app/style/images/yogurt_active.png",
		items: [
			{
				id: 19,
				title: "蓝莓鲜橙汁",
				subTitle: "Blueberry Orange",
				imgURL: "itemIMG/blueberry.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 28,
				capacity: 400,
			},
			{
				id: 20,
				title: "蓝莓鲜橙汁",
				subTitle: "Blueberry Orange",
				imgURL: "itemIMG/blueberry.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 28,
				capacity: 400,
			},
			{
				id: 21,
				title: "蓝莓鲜橙汁",
				subTitle: "Blueberry Orange",
				imgURL: "itemIMG/blueberry.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 28,
				capacity: 400,
			},
			{
				id: 22,
				title: "蓝莓鲜橙汁",
				subTitle: "Blueberry Orange",
				imgURL: "itemIMG/blueberry.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 28,
				capacity: 400,
			},
			{
				id: 23,
				title: "蓝莓鲜橙汁",
				subTitle: "Blueberry Orange",
				imgURL: "itemIMG/blueberry.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 28,
				capacity: 400,
			},
			{
				id: 24,
				title: "蓝莓鲜橙汁",
				subTitle: "Blueberry Orange",
				imgURL: "itemIMG/blueberry.png",
				discription: "牛油果的营养价值极高，富含多种维生素和多种矿质元素。雪梨富含维生素等微量元素。两者结合有助于美容、抗衰老、同时也能降血脂。",
				price: 28,
				capacity: 400,
			},
		]
	}

]
module.exports = MockTypeData;